# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# General settings
title: "Aleix Díaz - Blog"
name: "Aleix Díaz"
email: "your-email@example.com"
# logo: Add a logo image
locale: "es-ES"
description: >- # this means to ignore newlines until "baseurl:"
  Este es el lugar donde subo mis notas sobre ingeniería del software. La mayoría de artículos basados en iOS Swift"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Aleix88.github.io"
repository: "Aleix88/Aleix88.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Minimal mistakes settings
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

search: false # To enable/disable posts indexing and searching
defaults:
    # _posts
    - scope:
        path: ""
        type: posts
      values:
        layout: single
        author_profile: true
        show_date: true
        date_format: "%Y-%m-%d"
        read_time: true
        comments: false #To enable/disable comments on posts
        share: true
        related: true

# Social networks
social:
    links:
        - "https://www.linkedin.com/in/aleixdiazbaggerman"
        - "https://github.com/Aleix88"

# Author
author:
    name: "Aleix Díaz"
    avatar: "/assets/images/logo.png"
    bio: "iOS Developer"
    location: "BCN, Spain"
    links:
        - label: "Linkedin"
          icon: "fab fa-linkedin"
          url: "https://www.linkedin.com/in/aleixdiazbaggerman"
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/Aleix88"

# Footer
footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/aleixdiazbaggerman"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Aleix88"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache


# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-T0XEYX0RJB"
    anonymize_ip: false # default

atom_feed:
  hide: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
